/*
Author: Ahmed Elwakad
version: 1.0
date:12/8/2024
*/
#ifndef AFIO_INTERFACE_H
#define AFIO_INTERFACE_H

typedef enum {
AFIO_EXTI_GPIOA,
AFIO_EXTI_GPIOB,
AFIO_EXTI_GPIOC
}AFIO_EXTI_PORTS_t;


typedef enum{
AFIO_EXTI_LINE0 ,
AFIO_EXTI_LINE1 ,
AFIO_EXTI_LINE2 ,
AFIO_EXTI_LINE3 ,
AFIO_EXTI_LINE4 ,
AFIO_EXTI_LINE5 ,
AFIO_EXTI_LINE6 ,
AFIO_EXTI_LINE7 ,
AFIO_EXTI_LINE8 ,
AFIO_EXTI_LINE9 ,
AFIO_EXTI_LINE10,
AFIO_EXTI_LINE11,
AFIO_EXTI_LINE12,
AFIO_EXTI_LINE13,
AFIO_EXTI_LINE14,
AFIO_EXTI_LINE15
}AFIO_EXTI_LINE_t;

void MAFIO_voidSetEXTIConfiguration(AFIO_EXTI_LINE_t copy_Line ,AFIO_EXTI_PORTS_t copy_PortMap);

#endif